AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/*.rb'
    - '**/*.rake'
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/schema.rb'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'db/migrate/**/*'
    - 'cb_stem.gemspec'

Rails:
  Enabled: true

Documentation:
  Exclude:
    - 'app/controllers/**/*.rb'
    - 'app/models/**/*.rb'
    - 'app/helpers/**/*.rb'
    - 'db/migrate/*.rb'
    - 'config/**/*.rb'
    - 'lib/tasks/**/*.rake'
    - 'spec/support/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*.rb'
Metrics/LineLength:
  Max: 100
  Exclude:
    - 'db/migrate/*.rb'
    - 'db/seeds/*.rb'
    - 'config/**/*.rb'
    - 'Gemfile'
Metrics/ModuleLength:
  Exclude:
    - 'lib/cb_stem/extensions/views/helpers/view_helpers.rb'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/**/*.rb'
    - 'app/admin/**/*.rb'
    - 'lib/cb_stem/admin/**/*.rb'

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/MultilineAssignmentLayout:
  Enabled: true
Layout/DotPosition:
  EnforcedStyle: trailing

Style/OptionHash:
  Enabled: false
Style/FileName:
  Exclude:
    - 'Gemfile'
    - '.overcommit_gems.rb'
Style/FrozenStringLiteralComment:
  Enabled: false
  # waiting on https://github.com/rrosenblum/rubocop/commit/0c7f91b0abeb2dad305edfa301366b504bb7b734
Style/ClassAndModuleChildren:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
